apiVersion: v2
name: helm-failure-chart
description: A deliberately broken Helm chart with 10+ Kubernetes failure scenarios for AI agent troubleshooting demos
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: JustInCache
home: https://github.com/JustInCache/helm-failure-chart
sources:
  - https://github.com/JustInCache/helm-failure-chart
keywords:
  - kubernetes
  - troubleshooting
  - failure-scenarios
  - ai-agent
  - eks
  - demo
