# SCENARIO 3: Service selector mismatch → 0 endpoints
# Pods labeled "app: backend" but service selects "app: backend-api"
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hfc.fullname" . }}-backend
  labels:
    {{- include "hfc.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  # BUG: selector "backend-api" doesn't match pod label "backend"
  selector:
    app: backend-api
