apiVersion: v1
kind: Service
metadata:
  name: {{ include "hfc.fullname" . }}-frontend
  labels:
    {{- include "hfc.labels" . | nindent 4 }}
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
