# SCENARIO 9: RBAC wrong API group
# Deployments belong to apiGroup "apps", not "" (core)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hfc.fullname" . }}-role
  labels:
    {{- include "hfc.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # BUG: deployments are in "apps" apiGroup, not ""
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hfc.fullname" . }}-rolebinding
  labels:
    {{- include "hfc.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hfc.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "hfc.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
